### PR TITLE
Production Backend

### PR DESCRIPTION
**Pull request by dbrgn**
Hi @jpmeijers 

I started implementing support for the production backend.

The first part was easy, but now I'm not sure on how you want to handle the new message format.

First of all, removing croft would probably help to make the codebase easier. But I'm not sure if staging should still be supported at all. It makes the codebase much messier.

I'd probably suggest dropping support for croft / staging in the next version completely. People that still need that can use the old APK.

Another thing that was changed is the format of the data. Here's an example of the new message:

```json
{
    "port": 2,
    "counter": 105,
    "payload_raw": "aA==",
    "metadata": {
        "time": "2016-12-17T17:29:55.825510656Z",
        "frequency": 867.9,
        "modulation": "LORA",
        "data_rate": "SF7BW125",
        "coding_rate": "4/5",
        "gateways": [
            {
                "gtw_id": "eui-b827ebfffe4a5213",
                "timestamp": 1678625612,
                "time": "2016-12-17T17:29:55.799974Z",
                "channel": 7,
                "rssi": -77,
                "snr": 9.5,
                "latitude": 47.22628,
                "longitude": 8.82249,
                "altitude": 409
            }
        ]
    }
}
```

The `gateways` key has moved into `metadata`. Also, apps and devices are now identified by a custom identifier (appId and devId), not the EUIs anymore.

So the main blocker here for me are the following two questions:

- Can the old croft / staging stuff be removed?
- Will you do any changes to your mapper backend regarding EUIs, or should we just send appIDs and devIDs to your backend as appEUIs and devEUIs?

### CODE REVIEW

**Comment by jpmeijers** [comment]
_Can the old croft / staging stuff be removed?_ - Yes
_Will you do any changes to your mapper backend regarding EUIs, or should we just send appIDs and devIDs to your backend as appEUIs and devEUIs?_ - Yes that is how I am handling the MQTT imports too.

I'll have a look at the pull request ASAP, test it and merge. Did you test the app with a working node and these changes on your side already?

**Comment by dbrgn** [comment]
> I'll have a look at the pull request ASAP, test it and merge. Did you test the app with a working node and these changes on your side already?

Yes, but it doesn't work yet (since I didn't implement the format changes yet).

I'll start fixing those issues now though. I'll also remove the croft and staging parts.

**Comment by jpmeijers** [comment]
Ahh your reply came in just as I got the app running on my phone with a working node. Some JSON errors indeed because of the format difference. I think you will be able to fix this quicker than me. On holiday with slow internet and a single channel gateway to test at the moment ;)

Thanks a lot for the help to get this app fixed!

Let me know when you are done then I'll have a look, merge, test and publish to the store.

**Comment by jpmeijers** [comment]
Below a snippit of code where I extract info from the JSON received via MQTT on production. Note the if's where I check snr and id. In this code I strip the "eui-" part from the gateway id, but I'd suggest I'll do this server side, so do not do this in the app.

It should also answer your previous question as it shows how I use the device and application id's as they appear in the topic.

```
  node_addr = str(msg.topic.split("/")[2])
  appeui = str(msg.topic.split("/")[0])

    print("Version 2")
    print(data["metadata"]["time"] + ", " + data["payload_raw"])
    
    if(not "payload_raw" in data):
      print ("No payload in MQTT message")
      return

    values = parse_packet(data["payload_raw"])
    if(not values):
      return

    values = sanitize_data(values)
    if(not values):
      return

    values["server_time"] = data["metadata"]["time"]
    values["datarate"] = data["metadata"]["data_rate"]
    values["freq"] = data["metadata"]["frequency"]
    values["nodeaddr"] = node_addr
    values["appeui"] = appeui
    values["topic"] = msg.topic

    for gateway in data["metadata"]["gateways"]:
      print (gateway)
      values["rssi"] = gateway["rssi"]
      if("snr" in gateway):
        values["snr"] = gateway["snr"]
      if("id" in gateway):
        if(str(gateway["id"]).startswith("eui-")):
          values["gwaddr"] = str(gateway["id"])[4:].upper()
        else:
          values["gwaddr"] = str(gateway["id"])
      elif("gtw_id" in gateway):
        if(str(gateway["gtw_id"]).startswith("eui-")):
          values["gwaddr"] = str(gateway["gtw_id"])[4:].upper()
        else:
          values["gwaddr"] = str(gateway["gtw_id"])
      add_to_db(values)
```

**Comment by dbrgn** [comment]
Is it correct that the packets are sent to `https://ttnmapper.org/appapi/upload.php` while gateways are sent to `https://ttnmapper.org/api/update_gateway.php`?

**Comment by dbrgn** [comment]
Now everything should be working. Code is rebased against master.

Is the `Device` activity still being used? I couldn't find any usage in the app sourcecode.

**Comment by jpmeijers** [comment]
I think you are corect that the Devies activity is not used anymore. It seems like it was my first attempt to support both croft and staging (or a generic mqtt server) before I realised the JSON format was different. You are welcome to remove it.

**Comment by jpmeijers** [comment]
About that API. At the moment I should have Letsencrypt certs installed so HTTPS for the API should be OK. This was not the case in the past.

You are also correct in pointing out that the update_gateway endpoint is wrong. It should also be moved to the appapi directory. This is correct on the server (with backwards compatibility). This is also a relic from the past.

**Comment by jpmeijers** [comment]
Ok I am happy with this PR and will merge it in now. Thanks a lot again for the changes to make it work with the production backend!

**Comment by dbrgn** [comment]
Cool, thanks! Will go outside now with the LoPy :smiley:

**Pull request merged**
